
services:
  playwright:
    build: .
    container_name: playwright-tests
    working_dir: /app
    volumes:
      - .:/app:cached          # Mount project folder
    environment:
      - CI=true
    command: >
      sh -c "
      npx playwright test
      "