name: Playwright Tests

on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60


    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build & Run docker compose 
      run: docker compose up --build --abort-on-container-exit 
      
    - name: Upload allure results 
      uses: actions/upload-artifact@v4 
      with: 
        name: allure-results 
        path: allure-results 
    
    - name: Generate Allure report 
      uses: simple-elf/allure-report-action@v1.7 
      with: 
        allure_results: allure-results 
        allure_report: allure-report 
        
    - name: Upload Allure report 
      uses: actions/upload-artifact@v4 
      with: 
        name: allure-report 
        path: allure-report 